apiVersion: v1
kind: Service
metadata:
  name: gitops-node-service
spec:
  selector:
    app: gitops-node
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30036
